[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "immediate"

[[services]]
  http_bind = "0.0.0.0:8080"
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 8080
